config/routes.rb
Bob::Application.routes.draw do
  

 
  resources :videos

#  resources :questions
  match 'question' => "questions#create", :via => :post

  resources :categories do
    resources :awards do
        resources :recommendations 
    end
  end 
  
  
  resources :accounts, :as => :user
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :pages
  match 'home' => 'pages#home', :as => :home
  match 'overview-timeline' => 'pages#overview', :as => :overview
  match 'prizes' => 'pages#prizes', :as => :prizes
  match 'award-categories' => 'pages#awards', :as => :awardcat
  match 'admin' => 'pages#admin', :as => :admin
  match 'accounts-list' => 'pages#users_list', :as => :accounts_list
  match 'location' => 'categories#index', :as => :location
  
  match 'admin-awards' => 'pages#admin_awards', :as => :admin_awards
  match 'admin-recommendations' => 'pages#admin_recommendations', :as => :admin_recommendations
  match 'inbox' => 'pages#inbox', :as => :inbox  
  match 'question' => 'pages#question', :as => :question
  match 'thank-you' => 'pages#thankyou', :as => :thankyou
  match 'my-recommendations' => 'pages#recs', :as => :recs
  match 'photos-video' => 'pages#photos_video', :as => :photo_video
  
  #resources :recommendations, :shallow => true do
  resources :approvals 
  #end
  match 'toggle_decline' => 'approvals#toggle_decline'
  
  root :to => 'pages#home'
end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :embed, :presence => true
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :inbox_value, :if_recommendations
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= simple_form_for(@video) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <p>Set embed code width to 300px.<br><%= f.input :embed %></p>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<p><%= link_to "Back to Admin", admin_path %></p>

<table>
  <tr>
    <th>Name</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td class="first"><%= video.name %></td>
   
 
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<h3><%= link_to 'New Video', new_video_path %></h3>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @video.name %>
</p>

<p>
  <b>Embed:</b>
  <%= @video.embed %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>