config/routes.rb
Bob::Application.routes.draw do
  

 
  resources :videos

#  resources :questions
  match 'question' => "questions#create", :via => :post

  resources :categories do
    resources :awards do
        resources :recommendations 
    end
  end 
  
  
  resources :accounts, :as => :user
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :pages
  match 'home' => 'pages#home', :as => :home
  match 'overview-timeline' => 'pages#overview', :as => :overview
  match 'prizes' => 'pages#prizes', :as => :prizes
  match 'award-categories' => 'pages#awards', :as => :awardcat
  match 'admin' => 'pages#admin', :as => :admin
  match 'accounts-list' => 'pages#users_list', :as => :accounts_list
  match 'location' => 'categories#index', :as => :location
  
  match 'admin-awards' => 'pages#admin_awards', :as => :admin_awards
  match 'admin-recommendations' => 'pages#admin_recommendations', :as => :admin_recommendations
  match 'inbox' => 'pages#inbox', :as => :inbox  
  match 'question' => 'pages#question', :as => :question
  match 'thank-you' => 'pages#thankyou', :as => :thankyou
  match 'my-recommendations' => 'pages#recs', :as => :recs
  match 'photos-video' => 'pages#photos_video', :as => :photo_video
  
  #resources :recommendations, :shallow => true do
  resources :approvals 
  #end
  match 'toggle_decline' => 'approvals#toggle_decline'
  
  root :to => 'pages#home'
end

app/views/pages/admin.html.erb
<h1>Best of Bauer Administration</h1>

<h2>Choose from one of the following options to administrate</h2>


	<h3><%= link_to "Employees", accounts_list_path %></h3>
	<h3><%= link_to "Awards", admin_awards_path %></h3>
	<h3><%= link_to "Recommendations", admin_recommendations_path%></h3>
	<h3><%= link_to "Pages", pages_path %><h3>
	<h3><%= link_to "Videos", videos_path %> </h3>

app/views/pages/admin_awards.html.erb
<p><%= link_to "Back to Admin", admin_path %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Categories</th>
    <th></th>
    <th></th>
  </tr>

<% @awards.each do |award| %>
  <tr>
    <td class="first"><%= award.name %></td>
	<td class="second"><% award.categories.each do |category| %>
			<%= category.name %>,
		<% end %>
	</td>
 
    <td>
		<% if award.id == 16 || award.id == 15 %>
			<%= link_to 'Edit', edit_category_award_path(award.categories.first.id, award ) %>
		<% else %>
			<%= link_to 'Edit', edit_category_award_path(award.categories.first.id, award ) %>
		<% end %>
	</td>
    <td><%#= link_to 'Destroy', award, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<h3><%#= link_to 'New Award', new_category_award_path %></h3>

app/views/pages/admin_recommendations.html.erb
<h1>Listing recomendations</h1>

<p><%= link_to "Back to Admin", admin_path %></p>

<table>
  <tr>
    <th>Nominee</th>
    <th>Award</th>
    <th></th>
    <th></th>
	<th></th>
  </tr>

<% @recommendations.each do |recommendation| %>
  <tr>
    <td class="first"><%= recommendation.nominee %> |  </td>
    <td class="second"><%= recommendation.award.name unless recommendation.award.nil?  %> </td>
    <td><%= link_to 'View', category_award_recommendation_path(@category, recommendation.award.id, recommendation) %></td>
    <td><%= link_to 'Edit', edit_category_award_recommendation_path(@category, recommendation.award.id, recommendation) %></td>
 <td><%= link_to 'Destroy', category_award_recommendation_path(@category, recommendation.award.id, recommendation), confirm: 'Are you sure?', method: :delete %></td>  </tr>
<% end %>


</table>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/home.html.erb
<div id="page_body" class="home_text">

</div>

<div id="home_recommend"><%= link_to(image_tag("recommend_now.png", :border => "0"), location_path) %></div>

app/views/pages/inbox.html.erb
<h1>Inbox</h1>

<% if @approvals.present? %>
	<h2>Please review each approval listed</h2>
	<% @approvals.each do |approval|%>
		<h3>> <%= link_to approval.recommendation.nominee, approval %></h3>
	<% end %>
<% else %>
	No Recommendations need your approval!
<% end %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<p><%= link_to "Back to Admin", admin_path %></p>

<table>
  <tr>
    <th>Name</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td class="first"><%= page.name %></td>
    
    
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%#= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<h3><%= link_to 'New Page', new_page_path %></h3>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/overview.html.erb
<h1>OVERVIEW</h1>

<div id="page_body">
	<%=m @page.body  %>
</div>

app/views/pages/photos_video.html.erb
<div id="page_body">
		
	<h1>2012 Digital Shorts</h1>

	<% @videos.each do |video| %>
	<div class="video">
		<%=m video.embed %><br>
		<b><%= video.name %></b>
	</div>
	<% end %>
	<div class="clear"></div>

	<h1>2011 Digital Shorts</h1>
		<%= render 'shared/old_vids' %>
		
		
<!--		
<p>&nbsp;</p>
<h1>HIGHLIGHTS FROM BEST OF BAUER<br> 2010 – SUN VALLEY</h1>
<p><b>Nominee Trip</b> (May 16 – May 18, 2011): Best of Bauer Nominees were treated to an outdoor Northwest Adventure on one of their days in Seattle, as well as a boat ride to Blake Island for a Salmon Bake.<br><br> 

	Click <a href="http://www.facebook.com/groups/ebassociates/">here</a> to see photos on the Associate Facebook Page.  Not a member?  Click <a href="/pdf/facebook.pdf">here</a> for instructions on how to join!
</p>

<p>&nbsp;</p> 
	
<p><b>Award Ceremony</b> (May 18, 2011): As always, last year’s ceremony featured red carpet interviews, video segments, presentations by senior leaders, and award of the prized Best of Bauer statues.<br><br>

	Click <a href="http://www.facebook.com/groups/ebassociates/">here</a> to see photos and video on the Associate Facebook Page.  Not a member?  Click <a href="/pdf/facebook.pdf">here</a> for instructions on how to join! 
</p>

<p>&nbsp;</p>

<p><b>Winners Trip:</b> Sun Valley, ID (July 21 – July 25, 2011): Last year’s winners had an adventure in Sun Valley, ID! Winners and their guests were treated to white-water rafting, fly fishing, hiking, mountain biking, and ample opportunity to get outside to explore the beautiful surroundings.  On one morning, special guests Reggie and Zack Crist made a breakfast presentation and then joined the group for outdoor activities!<br><br>

	Click <a href="http://www.facebook.com/groups/ebassociates/">here</a> to see photos and video on the Associate Facebook Page.  Not a member?  Click <a href="/pdf/facebook.pdf">here</a> for instructions on how to join!</p>-->

	
</div>

app/views/pages/prizes.html.erb
<h1>Prizes</h1>

<div id="page_body">
		<%=m @page.body  %>
</div>

app/views/pages/question.html.erb
<h1>Ask a Question</h1>
<p>All Fields Required</p>
<%= simple_form_for @question, :url => url_for(:action => 'create', :controller => 'questions'), :method => 'post' do |f| %>
    <%= f.input :name, :required => true %>
	
		<% if current_user %>
			<p><b>Signed in as:</b> <%= current_user.email %></p>
			<%= hidden_field_tag( :email, current_user.email, :id => "question_name", :name => "question[email]") %>
		<% else %>
			<%= f.input :email, :required => true %>
		<% end %>
	<%= f.input :question, :as => :text, :required => true %>
    <%= f.button :submit, 'Send' %>
  <% end %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @page.name %>
</p>

<p>
  <b>Body:</b>
  <%= @page.body %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/thankyou.html.erb
<h1>Thank You</h1>

Thank you for creating a Recommendation!<br><Br>   If you did not provide a supervisor's email, then this recommendation will be on hold until you do.  To access it again, please click the link at the top right "Rec's". 