config/routes.rb
Bob::Application.routes.draw do
  

 
  resources :videos

#  resources :questions
  match 'question' => "questions#create", :via => :post

  resources :categories do
    resources :awards do
        resources :recommendations 
    end
  end 
  
  
  resources :accounts, :as => :user
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :pages
  match 'home' => 'pages#home', :as => :home
  match 'overview-timeline' => 'pages#overview', :as => :overview
  match 'prizes' => 'pages#prizes', :as => :prizes
  match 'award-categories' => 'pages#awards', :as => :awardcat
  match 'admin' => 'pages#admin', :as => :admin
  match 'accounts-list' => 'pages#users_list', :as => :accounts_list
  match 'location' => 'categories#index', :as => :location
  
  match 'admin-awards' => 'pages#admin_awards', :as => :admin_awards
  match 'admin-recommendations' => 'pages#admin_recommendations', :as => :admin_recommendations
  match 'inbox' => 'pages#inbox', :as => :inbox  
  match 'question' => 'pages#question', :as => :question
  match 'thank-you' => 'pages#thankyou', :as => :thankyou
  match 'my-recommendations' => 'pages#recs', :as => :recs
  match 'photos-video' => 'pages#photos_video', :as => :photo_video
  
  #resources :recommendations, :shallow => true do
  resources :approvals 
  #end
  match 'toggle_decline' => 'approvals#toggle_decline'
  
  root :to => 'pages#home'
end

app/models/award.rb
class Award < ActiveRecord::Base
    has_and_belongs_to_many :categories
    has_many :recommendations
    attr_accessible :name, :info, :category_ids
    
    scope :in_categories, lambda { |categories|
      joins(:categories).
      where(:awards_categories => { :category_id => categories } ).
      select("DISTINCT awards.*")
    }
    
    # Hard coding the ids for the store awards
      STORE_AWARD_IDS = [3,4,5]
      DIRECTOR_AWARD_IDS = [6]
      OPEN_AWARD_IDS = [7]
      # Class method to make checking for a store award easier
      # Usage:
      #   if Award.store_award?(params[:award_id])
      #   # do something
      #   else
      #   # do other thing
      #   end
      def self.store_award?(id_or_award)
        award = id_or_award.kind_of?(Award) ? id_or_award : find_by_id(id_or_award)
        award.store_award?
      end

      # true if the award's id is in the STORE_AWARD_IDS field
      # Usage:
      #   award = Award.find(params[:id])
      #   if award.store_award?
      #   # do thing
      #   else
      #   # do other thing
      #   end
      def store_award?
        STORE_AWARD_IDS.include?(id)
      end

      # convenience method, if it's not a store award it's an award for a person
      def person_award?
        !store_award?
      end
      
      
     
       def self.director_award?(id_or_award)
          award = id_or_award.kind_of?(Award) ? id_or_award : find_by_id(id_or_award)
          award.director_award?
        end

        def director_award?
          DIRECTOR_AWARD_IDS.include?(id)
        end
        
    
       def self.open_award?(id_or_award)
          award = id_or_award.kind_of?(Award) ? id_or_award : find_by_id(id_or_award)
          award.open_award?
        end

        def open_award?
          OPEN_AWARD_IDS.include?(id)
        end

      
    
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_filter :inbox_value, :if_recommendations
  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awards }
    end
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
    @award = Award.find(params[:id])
    @category = Category.find(params[:category_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/new
  # GET /awards/new.json
  def new
    @award = Award.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/1/edit
  def edit
    @category = Category.find(params[:category_id])
    @award = Award.find(params[:id])
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(params[:award])

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render json: admin_awards_path, status: :created, location: @award }
      else
        format.html { render action: "new" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /awards/1
  # PUT /awards/1.json
  def update
    @award = Award.find(params[:id])

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to admin_awards_path, notice: 'Award was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award = Award.find(params[:id])
    @award.destroy

    respond_to do |format|
      format.html { redirect_to awards_url }
      format.json { head :ok }
    end
  end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.erb
<%= form_for [@category, @award], :url => category_award_path do |f| %>

  <% if @award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% @award.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
   Categories<br />
<% for category in Category.find(:all)%>
	<%= check_box_tag "award[category_ids][]", category.id, @award.categories.include?(category)%>
	<%= category.name%>
<% end %>
    
  </div>

 <div class="field">
	<h2>Instructions on page editing</h2>
	# h1 tag<br>
	## h2 tag<br>
	### h3 tag - Add more "#" up to 6<br>
	-    List Items (hyphen, four spaces, item)<br>
	**This is a bold line**<br>
	_this is an italic line_<br>
	<a href="http://daringfireball.net/projects/markdown/syntax#list">Go Here</a> for more info on how to style text


  </div>

<div class="field">
    Award Info<br />
    <%= f.text_area :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing award</h1>

<%= render 'form' %>

<%= link_to 'Show', category_award_path(@award) %> |
<%= link_to 'Back', category_awards_path %>

app/views/awards/index.html.erb
<h1>Listing awards</h1>

<p><%= link_to "Back to Admin", admin_path %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Categories</th>
    <th></th>
    <th></th>
  </tr>

<% @awards.each do |award| %>
  <tr>
    <td class="first"><%= award.name %></td>
	<td class="second"><% award.categories.each do |category| %>
			<%= category.name %>,
		<% end %>
	</td>
 
    <td><%= link_to 'Edit', edit_award_path(award) %></td>
    <td><%= link_to 'Destroy', award, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<h3><%= link_to 'New Award', new_award_path %></h3>

app/views/awards/new.html.erb
<h1>New award</h1>

<%= render 'form' %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<h1><%= @award.name %></h1>


<div id="award_info">
  <%= m @award.info %>
</div>


<div id="award_recommendation">
<% if @award.id == 15 || @award.id == 16 %>

<% else %>		
	<%= link_to "Recommend A Collegue Now!", new_category_award_recommendation_path(@category, @award ), :class => "buttonOrange"%>	
<% end %>
</div>