config/routes.rb
Bob::Application.routes.draw do
  

 
  resources :videos

#  resources :questions
  match 'question' => "questions#create", :via => :post

  resources :categories do
    resources :awards do
        resources :recommendations 
    end
  end 
  
  
  resources :accounts, :as => :user
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :pages
  match 'home' => 'pages#home', :as => :home
  match 'overview-timeline' => 'pages#overview', :as => :overview
  match 'prizes' => 'pages#prizes', :as => :prizes
  match 'award-categories' => 'pages#awards', :as => :awardcat
  match 'admin' => 'pages#admin', :as => :admin
  match 'accounts-list' => 'pages#users_list', :as => :accounts_list
  match 'location' => 'categories#index', :as => :location
  
  match 'admin-awards' => 'pages#admin_awards', :as => :admin_awards
  match 'admin-recommendations' => 'pages#admin_recommendations', :as => :admin_recommendations
  match 'inbox' => 'pages#inbox', :as => :inbox  
  match 'question' => 'pages#question', :as => :question
  match 'thank-you' => 'pages#thankyou', :as => :thankyou
  match 'my-recommendations' => 'pages#recs', :as => :recs
  match 'photos-video' => 'pages#photos_video', :as => :photo_video
  
  #resources :recommendations, :shallow => true do
  resources :approvals 
  #end
  match 'toggle_decline' => 'approvals#toggle_decline'
  
  root :to => 'pages#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bob</title>
  <%= stylesheet_link_tag    "application"  %>
  <%= javascript_include_tag "application" %> 
  <%= csrf_meta_tags %>

</head>
<body>

<% if @page.present? && @page.name == "Home" %>	
	<div id="container" class="home" >
<% else %>
	<div id="container" class="interior">
<% end %>

	<div id="top">	
		
		<ul id="utility_nav">
				<% if user_signed_in? %>
				   <li id="signed_in_as">Signed in as <%= current_user.email %></li>
				   <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				    <li id="sign_up_in"><%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %></li>
				<% end %>
				
				<% if current_user.present? && current_user.admin == true %>
					<li><%= link_to "Admin", admin_path %></li>
				<% end %>
				
				<% if current_user.present? %>
					<li>
						<% if @my_recs.present? %>
							<%= link_to "My Rec's", recs_path%></li>
						<% end %>
					<li>
							<% if @approval_value.present? %>
								<%= link_to image_tag("email_open.png", :align => "right"), inbox_path %>
							<% else %>
							
							<% end %>
					</li>
			<% else %><% end %> 
		</ul>
		<ul id="main_nav">
			<li><%= link_to "Recommend Now!", location_path %></li>
			<li><%= link_to "Overview & Timeline", overview_path%></li>
			<li><%= link_to "Award Categories", awardcat_path%></li>
			<li><%= link_to "Prizes", prizes_path%></li>		
			<li><%= link_to "Photos & Video", photo_video_path%></li>
			<li id="last"><%= link_to "Questions", question_path %></li>
		</ul>
		<div class="clear"></div>
	</div>
	
	<div id="limiter">
		<% if flash[:notice] %>
		      <div id="notice"><%= flash[:notice] %></div>
		    <% end %>
		    <% if flash[:error] %>
		      <div id="error"><%= flash[:error] %></div>
		    <% end %>
		
		<div id="page_body">
		<%= yield %>
		</div>
	</div>


</div>
</body>
</html>